### ISSUE TITLE
Why wait for key press at end?

### ISSUE THREAD

**Issue by spth** [gicking/STM8_serial_flasher#12]
I can see the point of waiting for a key press at start, since the bootloader activation second would be hard to hit otherwise. But why at the end? I'd suggest to just drop the end wait and the -q option.

Philipp

**Comment by gicking** [comment]
I added it since I normally call this via double-click on a batch file (Win) respectively a shell-script (*ix). And sometimes I want to take a closer look at the output, that's all. 

However, point taken: I propose to keep the -q option but change the default to "no wait at end". Is this ok for you? That is VERY little effort and allows me to keep the window open if wanted

**Comment by spth** [comment]
Yes, that would do. Maybe rename the option as well?

Philipp

P.S.: After merging my work on binary files, you might want to add such a wait to the Error() function, since otherwise errors in reading binary files will not have the wait.

**Comment by gicking** [comment]
changed as proposed above
