### ISSUE TITLE
LIN support

### ISSUE THREAD

**Issue by spth** [gicking/STM8_serial_flasher#4]
According to ST documentation, on the STM8AF, the bootloader can be accessed via LINUART, too.

Philipp

**Comment by gicking** [comment]
actually I think that should already work. Since I have a suitable board available, I'll check it as soon as possible. So far I've never used it, because LINUART (for my high density device) requires reply mode, which is very slow. But I'll try it on Monday and let you know. 

Georg

**Comment by gicking** [comment]
flashing of the STM8AF(52AA) via LINUART tested successfully with separate Rx and Tx lines under MacOSX 10.10.. Testing with 1 line (as in LIN system) will follow tomorrow

Notes:
- with separate Rx and Tx lines (=2-wire) you have to use the "reply mode" (-u 2) as described in table 5 of the [STM8 bootloader manual](http://www.st.com/st-web-ui/static/active/en/resource/technical/document/user_manual/CD00201192.pdf?s_searchtype=keyword), and in the [Wiki](https://github.com/gicking/STM8_serial_flasher/wiki/Using-the-Software)
- with Rx and Tx connected (1-wire), e.g. behind a LIN transceiver, use "-u 1" instead to ignore the line echoes (test result pending)

**Comment by gicking** [comment]
Flashing via 1-wire interface and LINUART with reply mode tested (partially) successful (option “-u 1”)

Test setup:
- 1-wire simplex: PC :left_right_arrow: USB/RS232 adapter :left_right_arrow: [RS232/K-line adapter](https://vector.com/vi_cable_de.html?tab=3) :left_right_arrow: [LIN transceiver](http://www.nxp.com/documents/data_sheet/TJA1021.pdf) :left_right_arrow: STM8-LINUART
- Tested STM8AF52AA, STM8S208 and STM8S105
- Ok for Win8 up to 40kBaud. Above 40kBaud failed, probably due too low LIN slew-rate
- Failed for MacOSX 10.10 (`<error in 'bsl_sync()': wrong response 0x00 from BSL>`)
- Linux test pending 

-> in principal support for 1-wire simplex interface works. However, an issue exists under Posix, most likely timing. Next step is to fix fail under MacOSX and re-test under Linux (expect same behavior, since both use same Posix APIs)

**Comment by gicking** [comment]
tested ok with following modes: 2-wire duplex, 2-wire reply and 1-wire reply (e.g. LIN). For more details see [Wiki page](https://github.com/gicking/STM8_serial_flasher/wiki/Supported-Platforms)
