### ISSUE TITLE
Keep RAM routines in separate files

### ISSUE THREAD

**Issue by spth** [gicking/STM8_serial_flasher#8]
While we don't know yet what the license for the RAM routines will be, it might not be APL or APL-compatible. In that case, those RAM routines should not be linked into the program binary, but read at runtime from their files.
This would also allow distributions to not ship them, should the license turn out to be non-free.

Philipp

**Comment by gicking** [comment]
yeah, that's of course possible. However, it would make installation of the tool more troublesome, because the user needs to download and install the STM "Flash Loader Demonstrator" first, just to copy a few S19 files :-( 

I propose to see how issue #1 is resolved. If STM frees the RAM code (which I believe will be the case), I see no benefit in reading them at runtime...?

**Comment by spth** [comment]
Well, if the license allows redistribution, we could still have RAM routines files in the repository, and install them somewhere via "make install". But distributions that consider the license ínacceptable could still ship the program without the RAM routines.
E.g. Debian does package SDCC, but they do not include the files in device/non-free (currently just some headers for Microchip pic devices).

Philipp

**Comment by gicking** [comment]
obsolete after confirmation by ST support that now ultimate-liberty-v2 license applies (http://www.st.com/software_license_agreement_liberty_v2), which allows re-distribution
